# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Single-job pipeline: Run unit tests using pytest

pr:
  - master

jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6.9'
      Python37:
        python.version: '3.7.4'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '${python.version)'
    displayName: 'Set python version according to build matrix'
  - script: python -m pip install --upgrade pip
    displayName: 'Update pip'
  - script: pip install -r requirements.txt
    displayName: 'Install requirements'
  - script: pip install pytest-azurepipelines
    displayName: 'Install azure-specific dependencies'
  - script: python -m pytest tests/
    displayName: 'Run tests'
  - script: pip install .
    displayName: 'Check if installable using pip'
